### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by Beeblerox** [Yanrishatum/HLCC#1]
Can you provide the most simple example of how to compile empty Heaps project into executable.
I just can't figure out the structure of required json file to make HLCC work

**Comment by Yanrishatum** [comment]
Hm. I thought it's pretty straightforward. You don't have to generate json file, it is done by Haxe itself when it compiles .c source. I've added a bit more detailed usage instructions to readme :)

**Comment by Beeblerox** [comment]
@Yanrishatum Thank you! Will try it tonight
