### ISSUE TITLE
Compile static and dynamic library with HLCC

### ISSUE THREAD

**Issue by flashultra** [Yanrishatum/HLCC#4]
Would be possible to compile static ( .lib or .a ) and dynamic library ( .dll and .so)  using hlcc and hashlink ?
I was read about compiling library using hxcpp , but not sure is it possible with hashlink ?

**Comment by Yanrishatum** [comment]
I'm not sure it's possible, better ask this question on [Hashlink](/HaxeFoundation/hashlink) repo. HLCC in itself is just a small tool that automates compilation process, and made to just compile executables.

**Comment by flashultra** [comment]
Thank you.
