### ISSUE TITLE
win7 vs2015 build error

### ISSUE THREAD

**Issue by sonygod** [Yanrishatum/HLCC#5]
my project just build successful  on ubuntu +gcc ,

and I try to use hlcc ,I got this error.

        bin \ server / SocketEvent.h (23): error C2143: Syntax error: Missing ":" (before "constant")
        bin \ openfl / events / ErrorEvent.h (20): error C2143: Syntax error: Missing ":" (before "constant")
        bin \ web / proto / ErrorEventCS.h (21): error C2143: syntax error: missing ":" (before "constant")
        bin \ hl / init.c (8817): error C2059: syntax error: "constant"
        bin \ hl / init.c (8819): error C2275: "org__msgpack __ $ Encoder": illegal use of this type as an expression
        bin \ org / msgpack / Encoder.h (4): note: See the declaration of "org__msgpack __ $ Encoder"
        bin \ hl / init.c (8819): error C2146: syntax error: missing ";" (before the identifier "g $ _org_msgpack_Encoder")
        bin \ hl / init.c (8874): error C2059: syntax error: "constant"
        bin \ hl / init.c (8875): error C2275: "String": illegal to use this type as an expression
        bin \ _std / String.h (5): note: See the declaration for "String"
        bin \ hl / init.c (8875): error C2146: syntax error: missing ";" (before the identifier "s $ socket_heartbeat")
        bin \ hl / init.c (8876): error C2275: "server __ $ SocketEvent": illegal to use this type as an expression
        bin \ server / SocketEvent.h (4): note: See statement for "server __ $ SocketEvent"
        bin \ hl / init.c (8876): error C2146: syntax error: missing ";" (before the identifier "g $ _server_SocketEvent")
        bin \ hl / init.c (9095): error C2059: syntax error: "constant"
        bin \ hl / init.c (9096): error C2275: "String": illegal to use this type as an expression
        bin \ _std / String.h (5): note: See the declaration for "String"
        bin \ hl / init.c (9096): error C2146: syntax error: missing ";" (before the identifier "s $ game_over")
        bin \ hl / init.c (9097): error C2275: "web__proto __ $ GameEvent": illegal use of this type as an expression
        bin \ web / proto / GameEvent.h (4): note: See statement for "web__proto __ $ GameEvent"
        bin \ hl / init.c (9097): error C2146: syntax error: missing ";" (before the identifier "g $ _web_proto_GameEvent")

//------------------------------

    // Generated by HLC 4.1.0 (HL v4)
    #ifndef INC_server__SocketEvent
    #define INC_server__SocketEvent
    typedef struct _server__$SocketEvent *server__$SocketEvent;
    typedef struct _server__SocketEvent *server__SocketEvent;
    #include <hl/Class.h>
    #include <hl/BaseType.h>
    #include <_std/String.h>
    #include <openfl/events/Event.h>
    #include <haxe/io/Bytes.h>

    struct _server__$SocketEvent {
        hl_type *$type;
        hl_type* __type__;
        vdynamic* __meta__;
        varray* __implementedBy__;
        String __name__;
        vdynamic* __constructor__;
        String OPEN;
        String CLOSE;
        String MESSAGE;
        String ERROR;
        String HEARTBEAT;
    };
    struct _server__SocketEvent {
        hl_type *$type;
        bool bubbles;
        bool cancelable;
        vdynamic* currentTarget;
        int eventPhase;
        vdynamic* target;
        String type;
        bool __isCanceled;
        bool __isCanceledNow;
        bool __preventDefault;
        vvirtual* hander;
    };
    #endif

**Comment by sonygod** [comment]
[bin.zip](https://github.com/Yanrishatum/HLCC/files/4038833/bin.zip)

**Comment by Yanrishatum** [comment]
HLCC tools is not maintained and was made for pretty old HL version with extremely finicky setup.
You can do compilation manually following that guide:
https://gist.github.com/Yanrishatum/d69ed72e368e35b18cbfca726d81279a
Also since HL 1.1, there is command to generate Visual Studio project:
> hashlink post-compilation library : added ability to generate VisualStudio solution with `-D hlgen.makefile=vs2015`

https://github.com/HaxeFoundation/hashlink/releases

**Comment by sonygod** [comment]
thank you

**Comment by sonygod** [comment]
you mean like ? but it's seem not work

build.hxml 	
 
	 -cp src
	-D analyzer-optimize
	-main Main

	-hl test.hl

	-D hlgen.makefile=vs2015

**Comment by Yanrishatum** [comment]
This is not an HLCC issue. Note that project files would be generated only if you output HLC, not hl bytecode and you. Also I never used it in the first place, because when I compile - I do it from command-line.

**Comment by sonygod** [comment]
mark

haxelib run hashlink build D:\project\testhashlinkandvs\out -D hlgen.makefile=vs2015
